id: template-rust
name: Rust app boilerplate
intro: A boilerplate for building a Rust application. Fork this repo and start building your own app quikly.
description: |
  A boilerplate for building a Rust application
  Fork this repo and start building your own app quikly.
  This template is a simple Rust application that can be used as a starting point for building your own app.
demoUrl: "https://rust.demo.dollardeploy.dev/"
logo: https://avatars.githubusercontent.com/u/5430905
requirements:
  memory: 1024
  cpu: 1
  storage: 10
deployTime: ~3 minutes
tags:
  - rust
  - template
  - oss
app:
  type: native
  repositoryUrl: https://github.com/dollardeploy/example-rust
  sourceBranch: main
  startCmd: ./target/release/example-rust-web
  mainPort: 3000
