id: twenty-crm
name: Twenty CRM
intro: "The #1 Open-Source CRM"
logo: https://github.com/twentyhq/twenty/raw/main/packages/twenty-website/public/images/core/logo.svg
deployTime: ~3 minutes
description: |
  The #1 Open-Source CRM Modern, powerful, affordable platform to manage your customer relationships. Version 0.50.1. https://twenty.com/releases
requirements:
  memory: 2048
  cpu: 2
  storage: 10
services:
  - docker
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourcePath: twenty-crm
  sourceBranch: main
  env:
    APP_SECRET: ${GENERATED_HASH}
    SERVER_URL: ${APP_URL}
    PGPASSWORD_SUPERUSER: ${GENERATED_PWD}
    TAG: v0.52.9
    STORAGE_TYPE: local
    PORT: 3000
    PG_DATABASE_HOST: db
    SIGN_IN_PREFILLED: true
  preStartCmd: bash ./fixdocker.sh
  files:
    - path: fixdocker.sh
      content: |
        #!/bin/bash
        mkdir -p data
        mkdir -p data/tmp
        mkdir -p data/local
        mkdir -p data/db/pgroot/data
        # TwentyCRM expects to run as 1000:1000
        sudo chown 1000:1000 data/local
        sudo chown 1000:1000 data/tmp
        # The server must be started by the user that owns the data directory.
        sudo chown root:root data/db
        # UID/GID which runs postgres in db container
        sudo chown 101:103 -R data/db/pgroot
        # data directory "/home/postgres/pgdata/pgroot/data" has invalid permissions 
        # Permissions should be u=rwx (0700) or u=rwx,g=rx (0750)
        sudo chmod 0700 data/db/pgroot/data
