services:
    server:
        image: twentycrm/twenty:${TAG}
        user: "$USER_UID:$USER_GID"
        volumes:
            - ./data/local:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
            - ./data/tmp:/app/docker-data
        ports:
            - '127.0.0.1:$PORT:3000'
        env_file: ".env"
        environment:
            PORT: 3000
            PG_DATABASE_URL: postgres://${PGUSER_SUPERUSER:-postgres}:${PGPASSWORD_SUPERUSER:-postgres}@${PG_DATABASE_HOST:-db}:5432/postgres
            SERVER_URL: ${SERVER_URL}
            FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
            FRONTEND_URL: ${FRONTEND_URL:-$SERVER_URL}
            REDIS_URL: redis://redis:6379

            ENABLE_DB_MIGRATIONS: 'true'
            DISABLE_DB_MIGRATIONS: 'false'

            SIGN_IN_PREFILLED: ${SIGN_IN_PREFILLED}
            STORAGE_TYPE: ${STORAGE_TYPE}
            STORAGE_S3_REGION: ${STORAGE_S3_REGION}
            STORAGE_S3_NAME: ${STORAGE_S3_NAME}
            STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

            APP_SECRET: ${APP_SECRET}
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:3000/healthz
            interval: 5s
            timeout: 5s
            retries: 10
        restart: always

    worker:
        image: twentycrm/twenty:${TAG}
        command: ['yarn', 'worker:prod']
        env_file: ".env"
        user: "$USER_UID:$USER_GID"
        volumes:
            - ./data/local:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
        environment:
            PG_DATABASE_URL: postgres://${PGUSER_SUPERUSER:-postgres}:${PGPASSWORD_SUPERUSER:-postgres}@${PG_DATABASE_HOST:-db}:5432/default
            SERVER_URL: ${SERVER_URL}
            FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
            REDIS_URL: redis://redis:6379

            ENABLE_DB_MIGRATIONS: 'false' # it already runs on the server

            STORAGE_TYPE: ${STORAGE_TYPE}
            STORAGE_S3_REGION: ${STORAGE_S3_REGION}
            STORAGE_S3_NAME: ${STORAGE_S3_NAME}
            STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

            APP_SECRET: ${APP_SECRET}
        depends_on:
            db:
                condition: service_healthy
            server:
                condition: service_healthy
        restart: always

    db:
        image: twentycrm/twenty-postgres-spilo:${TAG}
        volumes:
            - ./data/db:/home/postgres/pgdata
        environment:
            PGUSER_SUPERUSER: ${PGUSER_SUPERUSER:-postgres}
            PGPASSWORD_SUPERUSER: ${PGPASSWORD_SUPERUSER:-postgres}
            ALLOW_NOSSL: 'true'
            SPILO_PROVIDER: 'local'
        healthcheck:
            test: pg_isready -U ${PGUSER_SUPERUSER:-postgres} -h localhost -d postgres
            interval: 5s
            timeout: 5s
            retries: 10
        restart: always

    redis:
        image: redis
        restart: always
