---
id: cal-com-docker
name: Cal.com
intro: Cal.com is an open-source scheduling infrastructure for absolutely everyone.
logo: https://raw.githubusercontent.com/calcom/cal.com/main/apps/web/public/android-chrome-192x192.png
experimental: false
tags:
  - oss
  - scheduling
  - calendar
  - booking
  - meeting
requirements:
  memory: 8096
  cpu: 2
  storage: 20
app:
  type: docker-compose
  env:
    NEXT_PUBLIC_WEBAPP_URL: https://${APP_HOSTNAME}
    API_PORT: 3001
    NEXT_PUBLIC_API_V2_URL: https://${APP_HOSTNAME}/api/v2
    NEXT_PUBLIC_WEBSITE_TERMS_URL: https://example.com
    NEXT_PUBLIC_WEBSITE_PRIVACY_POLICY_URL: https://example.com
    NEXT_PUBLIC_LICENSE_CONSENT: agree
    CALCOM_TELEMETRY_DISABLED: 1
    NEXTAUTH_SECRET: "${GENERATED_HASH}"
    CALENDSO_ENCRYPTION_KEY: "${GENERATED_HASH}"
    POSTGRES_USER: unicorn_user
    POSTGRES_PASSWORD: magical_password
    POSTGRES_DB: calendso
    DATABASE_HOST: database:5432
    DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}"
    DATABASE_DIRECT_URL: ${DATABASE_URL}
    EMAIL_FROM: hello@example.com
    DOCKER_COMPOSE_WAIT_TIMEOUT: 600
    REDIS_URL: redis://redis:6379
    PORT: 3000
  repositoryUrl: https://github.com/calcom/cal.com
  sourceBranch: main
  dockerComposeFile: docker-compose.yml
  preStartCmd: bash ./fixdocker.sh
  files:
    - path: fixdocker.sh
      content: |
        #!/bin/bash
        sed -e "s/- 3000:3000/- 127.0.0.1:\$PORT:3000/g" -i docker-compose.yml
        sed -e "s/studio:/studio-optional:\n    profiles: [withstudio]/g" -i docker-compose.yml  
introVideoUrl: https://www.youtube-nocookie.com/embed/60HJt8DOVNo
deployTime: "~10 minutes"
description: Cal.com is a scheduling infrastructure for everyone. It's an open source
  alternative to Calendly that allows you to schedule meetings efficiently and integrate
  with various calendar services.
services:
  - docker

