id: evolution-api
name: Evolution API
intro: Evolution API is an open-source WhatsApp integration API
tags:
  - oss
  - whatsapp
  - instant-messaging
  - customer-support
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates/
  sourcePath: evolution-api
  env:
    PORT: 8080
    IMAGE_TAG: v1.8.6
    SERVER_TYPE: http
    SERVER_PORT: ${PORT}
    SERVER_URL: ${APP_URL}
    SENTRY_DSN: ""
    CORS_ORIGIN: "*"
    CORS_METHODS: "GET,POST,PUT,DELETE"
    CORS_CREDENTIALS: "true"
    LOG_LEVEL: "ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET"
    LOG_COLOR: "true"
    LOG_BAILEYS: "error"
    EVENT_EMITTER_MAX_LISTENERS: "50"
    DEL_INSTANCE: "false"
    DATABASE_PROVIDER: "postgresql"
    DATABASE_CONNECTION_URI: "postgresql://user:pass@postgres:5432/evolution?schema=public"
    DATABASE_CONNECTION_CLIENT_NAME: "evolution_exchange"
    DATABASE_SAVE_DATA_INSTANCE: "true"
    DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
    DATABASE_SAVE_MESSAGE_UPDATE: "true"
    DATABASE_SAVE_DATA_CONTACTS: "true"
    DATABASE_SAVE_DATA_CHATS: "true"
    DATABASE_SAVE_DATA_LABELS: "true"
    DATABASE_SAVE_DATA_HISTORIC: "true"
    DATABASE_SAVE_IS_ON_WHATSAPP: "true"
    DATABASE_SAVE_IS_ON_WHATSAPP_DAYS: "7"
    DATABASE_DELETE_MESSAGE: true
    RABBITMQ_ENABLED: false
    SQS_ENABLED: false
    WEBSOCKET_ENABLED: false
    PUSHER_GLOBAL_ENABLED: false
    WA_BUSINESS_TOKEN_WEBHOOK: evolution
    WA_BUSINESS_URL: https://graph.facebook.com
    WA_BUSINESS_VERSION: v20.0
    WA_BUSINESS_LANGUAGE: en_US
    WEBHOOK_GLOBAL_ENABLED: false
    WEBHOOK_GLOBAL_URL: ""
    CONFIG_SESSION_PHONE_CLIENT: Evolution API
    CONFIG_SESSION_PHONE_NAME: Chrome
    CONFIG_SESSION_PHONE_VERSION: 2.3000.1015901307
    QRCODE_LIMIT: 30
    QRCODE_COLOR: '#175197'
    TYPEBOT_ENABLED: false
    CHATWOOT_ENABLED: false
    OPENAI_ENABLED: false
    DIFY_ENABLED: false
    CACHE_REDIS_ENABLED: true
    CACHE_REDIS_URI: redis://redis:6379/6
    CACHE_REDIS_TTL: 604800
    CACHE_REDIS_PREFIX_KEY: evolution
    CACHE_REDIS_SAVE_INSTANCES: false
    CACHE_LOCAL_ENABLED: false
    S3_ENABLED: false
    AUTHENTICATION_API_KEY: ${GENERATED_HASH}
    AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: true
    LANGUAGE: en
deployTime: "~10 minutes"
description: |
  Evolution API is a messaging service that allows you to send and receive messages from your application,
  compatible with WhatsApp, Chatwoot, and more.
requirements:
  memory: 4096
  cpu: 2
  storage: 20
services:
  - docker

