id: erpnext
name: Frappe - ERPNext
intro: "ERPNext is a free and open-source integrated Enterprise resource planning"
logo: https://avatars.githubusercontent.com/u/836974
experimental: true
deployTime: "~10 minutes"
introVideoUrl: https://www.youtube-nocookie.com/embed/RjTipQpUvNQ
description: |
  ERPNext is a full-featured business management solution that helps SMEs
  to record all their business transactions in a single system. With ERPNext, SMEs
  can make informed, fact-based, timely decisions to remain ahead in the competition.
  It serves as the backbone of a business adding strength, transparency, and control
  to your growing enterprise.
requirements:
  memory: 4096
  cpu: 2
  storage: 20
services:
  - docker
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates/
  sourcePath: erpnext
  dockerComposeFile: pwd.yml
  preStartCmd: bash ./fixdocker.sh
  env:
    - ADMIN_PASSWORD: "${GENERATED_PWD}"
  files:
    - path: fixdocker.sh
      content: |
        #!/bin/bash
        sed -r -i "s/\"8080:8080\"/\"127.0.0.1:8080:8080\"/g" pwd.yml

