id: frappe-erpnext
name: Frappe - ERPNext
intro: "ERPNext is a free and open-source integrated Enterprise resource planning"
logo: https://avatars.githubusercontent.com/u/836974
experimental: true
deployTime: ~5 minutes
description: |
  Proprietary ERPs are expensive, limiting, and rigid. Businesses are left with two choices, either spend through the roof on SAP, NetSuite, Oracle, etc., or use multiple disconnected apps leading to manual work, poor visibility, and broken traceability. What if there is a better way?

  ERPNext is a 100% open-source ERP with a modern, comprehensive, and user-friendly enterprise resource planning solution. We don't have any features hidden behind expensive paywalls. Everything is yours to use, modify, or resell giving you full freedom, control, and flexibility.
requirements:
  memory: 2048
  cpu: 2
  storage: 10
services:
  - docker
app:
  type: docker-compose
  repositoryUrl: https://github.com/frappe/frappe_docker
  sourceBranch: main
  dockerComposeFile: pwd.yml
 
