id: erpnext
name: Frappe - ERPNext
intro: "ERPNext is a free and open-source integrated Enterprise resource planning"
logo: https://avatars.githubusercontent.com/u/836974
tags:
  - erp
  - business-management
  - oss
  - frappe
experimental: true
deployTime: "~10 minutes"
introVideoUrl: https://www.youtube-nocookie.com/embed/RjTipQpUvNQ
description: |
  ERPNext is a full-featured business management solution that helps SMEs
  to record all their business transactions in a single system. With ERPNext, SMEs
  can make informed, fact-based, timely decisions to remain ahead in the competition.
  It serves as the backbone of a business adding strength, transparency, and control
  to your growing enterprise.
requirements:
  memory: 4096
  cpu: 2
  storage: 20
services:
  - docker
postLaunchNote: |
  Username is `Administrator` and password is `${ADMIN_PASSWORD}`.
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates/
  sourcePath: erpnext
  dockerComposeFile: docker-compose.yml
  env:
    ADMIN_PASSWORD: "${GENERATED_PWD}"
    PORT: 8080
