version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:${BASEROW_VERSION:-1.34.5}
    environment:
      BASEROW_PUBLIC_URL: $BASEROW_PUBLIC_URL
      SECRET_KEY: $SECRET_KEY
      DATABASE_PASSWORD: postgres
      REDIS_PASSWORD: redis
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
