# https://github.com/n8n-io/n8n-hosting/tree/main/docker-compose/withPostgresAndWorker

id: n8n
name: N8N
intro: Free and source-available fair-code licensed workflow automation tool.
logo: https://avatars.githubusercontent.com/u/45487711
deployTime: ~5 minutes
description: |
  n8n helps you connect any app with an API to any other, and manipulate its data with little or no code.
  It's an easy-to-use, user-friendly and highly customizable service, which uses a visual workflow editor
  instead of writing code.
requirements:
  memory: 2048
  cpu: 1
  storage: 10
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourcePath: n8n
  sourceBranch: main # Or specify a specific version tag if needed
  dockerComposeFile: docker-compose.yml
  env:
    # Check for more env vars: https://docs.n8n.io/hosting/configuration/environment-variables/
    PORT: 5678
    N8N_HOST: ${APP_HOSTNAME}
    N8N_PORT: ${PORT}
    N8N_PROTOCOL: https
    WEBHOOK_URL: ${APP_URL}
    NODE_ENV: production
    GENERIC_TIMEZONE: UTC
    DB_TYPE: postgresdb
    DB_POSTGRESDB_HOST: postgres
    DB_POSTGRESDB_PORT: 5432
    DB_POSTGRESDB_DATABASE: ${POSTGRES_DATABASE}
    DB_POSTGRESDB_USER: ${POSTGRES_USER}
    DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
    N8N_ENCRYPTION_KEY: ${GENERATED_HASH}
