version: "3"

services:
    app:
        image: codelit/courselit-app:latest
        env_file: .env
        ports:
            - "${PORT:-3000}:${PORT:-3000}"
        restart: on-failure
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: courselit
            MONGO_INITDB_ROOT_PASSWORD: 123456