id: template-deno
name: Deno app boilerplate
intro: A boilerplate for building a Deno application. Fork this repo and start building your own app quickly.
description: |
  A boilerplate for building a Deno application
  Fork this repo and start building your own app quickly.
  This template is a simple Deno application that can be used as a starting point for building your own app.
logo: https://avatars.githubusercontent.com/u/42048915
experimental: true
requirements:
  memory: 1024
  cpu: 1
  storage: 10
deployTime: ~3 minutes
tags:
  - deno
  - typescript
  - template
  - oss
app:
  type: deno
  repositoryUrl: https://github.com/huksley/example-deno
  sourceBranch: main
  env:
    PORT: 3000
