services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    user: "$USER_UID:$USER_GID"
    volumes:
      - ./data:/data
    ports:
      - ${PORT}:8025
      - ${PORT_SMTP:-1025}:1025
      - ${PORT_POP3:-1110}:1110
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: ${MP_SMTP_AUTH_ACCEPT_ANY:-0}
      MP_SMTP_AUTH_ALLOW_INSECURE: ${MP_SMTP_AUTH_ALLOW_INSECURE:-1}
      MP_MAX_AGE: ${MP_MAX_AGE:-30d}
      MP_SMTP_RELAY_ALL: ${MP_SMTP_RELAY_ALL:-0}
      MP_SMTP_RELAY_HOST: ${MP_SMTP_RELAY_HOST:-}
      MP_SMTP_RELAY_PORT: ${MP_SMTP_RELAY_PORT:-25}
      MP_SMTP_RELAY_STARTTLS: ${MP_SMTP_RELAY_STARTTLS:-false}
      MP_SMTP_RELAY_ALLOW_INSECURE: ${MP_SMTP_RELAY_ALLOW_INSECURE:-false}
      MP_SMTP_RELAY_AUTH: ${MP_SMTP_RELAY_AUTH:-none}
      MP_SMTP_RELAY_USERNAME: ${MP_SMTP_RELAY_USERNAME:-}
      MP_SMTP_RELAY_PASSWORD: ${MP_SMTP_RELAY_PASSWORD:-}
      MP_SMTP_RELAY_SECRET: ${MP_SMTP_RELAY_SECRET:-}
      MP_SMTP_RELAY_RETURN_PATH: ${MP_SMTP_RELAY_RETURN_PATH:-}
      MP_SMTP_RELAY_OVERRIDE_FROM: ${MP_SMTP_RELAY_OVERRIDE_FROM:-}
      MP_SMTP_RELAY_ALLOWED_RECIPIENTS: ${MP_SMTP_RELAY_ALLOWED_RECIPIENTS:-}
      MP_SMTP_RELAY_BLOCKED_RECIPIENTS: ${MP_SMTP_RELAY_BLOCKED_RECIPIENTS:-}
