id: solid-nextjs
name: Solid Next.js (Free)
intro: Solid free Next.js SaaS/Startup template (Next 16, React 19, Tailwind)
tags: [nextjs, template, saas, marketing]
app:
  type: next
  repositoryUrl: https://github.com/NextJSTemplates/solid-nextjs
  sourceBranch: main
  mainPort: 3000

