id: pterodactyl
name: Pterodactyl
intro: Open-source game server management panel built for performance, security, and extensibility using Docker containers.
logo: https://pterodactyl.io/logos/pterry.svg
tags:
  - devops
  - server-management
  - gaming
experimental: true
requirements:
  memory: 4096
  cpu: 4
  storage: 50
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourceBranch: main
  sourcePath: pterodactyl
  dockerComposeFile: docker-compose.yml
  env:
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "admin@localhost"
    # MySQL section
    MYSQL_PASSWORD: "${GENERATED_PWD}"
    MYSQL_ROOT_PASSWORD: "${GENERATED_PWD}"
    # Mail section
    MAIL_FROM: "noreply@localhost"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"
services:
  - docker
deployTime: ~5 minutes
description: |
  Pterodactyl is a modern, secure, and scalable game server
  management platform. Built with PHP, React, and Go, it
  isolates each game server in its own Docker container to maximize
  security and stability. The web-based interface provides real-time
  WebSocket consoles, role-based user access, a robust API, and SFTP file management.
  Designed for both hobbyists and enterprises, it supports Minecraft, CS:GO, Rust, ARK, and more.