id: pterodactyl
name: Pterodactyl
intro: Open-source game server management panel built for performance, security, and extensibility using Docker containers.
logo: https://pterodactyl.io/logos/pterry.svg
tags:
  - devops
  - game-hosting
  - server-management
requirements:
  memory: 2048
  cpu: 2
  storage: 20
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourceBranch: main
  sourcePath: pterodactyl
  dockerComposeFile: docker-compose.yml
  postStartCmd: source .env && docker compose exec panel php artisan p:user:make --email=${ADMIN_EMAIL} --password=${ADMIN_PASSWORD} --admin=1 --username=${ADMIN_USERNAME} --name-first=Test --name-last=Test || true
  env:
    PORT: "802"
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "admin@localhost"
    HASHIDS_SALT: "${GENERATED_PWD}${GENERATED_PWD}"
    # MySQL section
    MYSQL_PASSWORD: "${GENERATED_PWD}"
    MYSQL_ROOT_PASSWORD: "${GENERATED_PWD}"
    # Mail section
    MAIL_FROM: "noreply@localhost"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"
    # Credentials
    ADMIN_EMAIL: "${USER_EMAIL}"
    ADMIN_USERNAME: "admin"
    ADMIN_PASSWORD: "${GENERATED_PWD}"
    # Wings
    PORT_PANEL: "8080"
    PORT_SFTP: "2022"
    TZ: "${APP_TIMEZONE}"
    WINGS_UID: "0"
    WINGS_GID: "0"
    WINGS_USERNAME: "admin"
services:
  - docker
deployTime: ~5 minutes
postLaunchNote: Use username `admin` and password `${ADMIN_PASSWORD}` to login.
description: |
  Pterodactyl is a modern, secure, and scalable game server anagement platform. 
  Built with PHP, React, and Go, it isolates each game server in its own Docker container
  to maximize security and stability. The web-based interface provides real-time
  WebSocket consoles, role-based user access, a robust API, and SFTP file management.
  Designed for both hobbyists and enterprises, it supports Minecraft, CS:GO, Rust, ARK, and more.
