version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "${MYSQL_PASSWORD}"
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  panel:
    &panel-environment
    APP_URL: "${APP_URL}"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "${APP_TIMEZONE}"
    APP_SERVICE_AUTHOR: "${APP_SERVICE_AUTHOR}"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: ${MAIL_FROM}
    MAIL_DRIVER: ${MAIL_DRIVER}
    MAIL_HOST: ${MAIL_HOST}
    MAIL_PORT: ${MAIL_PORT}
    MAIL_USERNAME: ${MAIL_USERNAME}
    MAIL_PASSWORD: ${MAIL_PASSWORD}
    MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    networks:
      - pterodactyl0
    ports:
      - "${PORT_WINGS:-8080}:8080"
      - "${PORT_SFTP}:2022"
    environment:
      TZ: "${APP_TIMEZONE}"
      WINGS_UID: "${WINGS_UID}"
      WINGS_GID: "${WINGS_GID}"
      WINGS_USERNAME: "${WINGS_USERNAME}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "./wings/config:/etc/pterodactyl"
      - "./var:/var/lib/pterodactyl"
      - "./logs:/var/log/pterodactyl"
      - "./tmp:/tmp/pterodactyl/"
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "${PORT}:80"
    links:
      - database
      - cache
    volumes:
      - "./var/:/app/var/"
      - "./nginx/:/etc/nginx/http.d/"
      - "./certs/:/etc/letsencrypt/"
      - "./logs/:/app/storage/logs/"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
      TRUSTED_PROXIES: "*"
      HASHIDS_SALT: "${HASHIDS_SALT}"
      HASHIDS_LENGTH: 8
      PTERODACTYL_TELEMETRY_ENABLED: false
networks:
  pterodactyl0:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: ptero0
