id: vercel-commerce
name: Vercel Commerce
tags:
  - template
logo: "https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_light_background.png"
intro: The fastest way to build an online store with Next.js and Vercel.
experimental: true
deployTime: "~1 minute"
description: |
  Example template of NextJS based commerce app.

  FIXME: Requires shopify credentials or else it will fail to start.
requirements:
  memory: 1024
  cpu: 1
  storage: 10
app:
  repositoryUrl: "https://github.com/vercel/commerce"
  sourceBranch: main
  type: next
  env:
    NEXT_PUBLIC_VERCEL_URL: "${APP_URL}"
    PORT: "3002"
    COMPANY_NAME: "Example Inc."
    TWITTER_CREATOR: "@example"
    TWITTER_SITE: "https://example.com"
    SITE_NAME: "Next.js Commerce with DollarDeply"
    SHOPIFY_REVALIDATION_SECRET: changeme
    SHOPIFY_STOREFRONT_ACCESS_TOKEN: changeme
    SHOPIFY_STORE_DOMAIN: changeme.myshopify.com
