id: local-ai-cpu
name: Local AI (CPU)
intro: >-
  Local AI is an open-source, self-hostable online OpenAI API compatible service
  with chatbot UI.
logo: https://github.com/mudler/LocalAI/blob/master/docs/static/android-chrome-192x192.png?raw=true
requirements:
  memory: 4096
  cpu: 2
  storage: 60
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates/
  sourcePath: local-ai-cpu
  sourceBranch: main
  dockerComposeFile: docker-compose.yml
  # Request user IP address to be set in the app
  allowAccessFrom: "${USER_IPADDRESS}"
  env:
    PORT: 8080
introVideoUrl: https://www.youtube-nocookie.com/embed/Xh57mMlfuMk
deployTime: ~20 minutes
description: >-
  Local AI is an open-source, self-hostable online OpenAI API compatible service
  with chatbot UI.
services:
  - docker
