version: '3.7'
services:
  mcdash:
    image: germannewsmaker/mcdash
    container_name: MCDash
    restart: unless-stopped
    volumes:
      - mcdash:/app/data
    ports:
      - "${PORT}:${PORT}"
      - "${MINECRAFT_PORT}:${MINECRAFT_PORT}"
      - "${ADDITIONAL_PORTS:-}:${ADDITIONAL_PORTS:-}"
    network_mode: host
volumes:
  mcdash:
