id: nextjs-boilerplate
name: Next.js 16 Boilerplate
tags:
  - template
  - nextjs
  - typescript
intro: Boilerplate for NextJS 16 to get you started
logo: "https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_light_background.png"
deployTime: ~1 minute
description: This example nicely shows how you can deploy NextJS app to any host.
requirements:
  memory: 1024
  cpu: 1
  storage: 10
app:
  repositoryUrl: "https://github.com/dollardeploy/nextjs-boilerplate"
  sourceBranch: main
  type: next
  mainPort: 3000

