id: wordpress
name: WordPress
intro: The World's Most Popular CMS
logo: https://avatars.githubusercontent.com/u/276006
deployTime: ~3 minutes
tags:
  - cms
  - oss
  - blog
  - website
  - popular
description: |
  WordPress is open source software you can use to create a beautiful website, blog, or app.
requirements:
  memory: 1024
  cpu: 1
  storage: 10
services:
  - docker
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourcePath: wordpress
  sourceBranch: main
  mainPort: 8080
  env:
    MYSQL_ROOT_PASSWORD: ${GENERATED_PWD}
    PUBLIC_URL: ${APP_URL}
    PORT: "8080"
  preStartCmd: bash ./fixdocker.sh
  files:
    - path: fixdocker.sh
      content: |
        #!/bin/bash
        mkdir -p ./data/db
        mkdir -p ./wordpress
        sudo chown -R 999:999 ./data/db
