services:
  sse:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${PORT:-8096}:8096"
    volumes:
      - ./data:/app/data
    environment:
      - FRAPPE_URL=${FRAPPE_URL:-http://localhost:8000}
      - FRAPPE_API_KEY=${FRAPPE_API_KEY:-frappe}
      - FRAPPE_API_SECRET=${FRAPPE_API_SECRET:-123}
      - PORT=${PORT:-8096}
