id: dozzle
name: Dozzle
intro: A simple, lightweight web interface for monitoring Docker containers.
description: |
  Dozzle is a simple, lightweight web interface for monitoring Docker containers.
  It provides a real-time view of all your containers, with detailed information
  about each container's status, logs, and metrics.
logo: https://dozzle.dev/logo.svg
requirements:
  memory: 1024
  cpu: 1
  storage: 2
deployTime: ~3 minutes
tags:
  - monitoring
  - devops
  - oss
experimental: true
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourceBranch: main
  sourcePath: dozzle
  dockerComposeFile: docker-compose.yml
  env:
    PORT: "8080"
    DOZZLE_AUTH_PROVIDER: simple
    DOZZLE_ENABLE_ACTIONS: true
    DOZZLE_ENABLE_SHELL: true
    DOZZLE_AUTH_EMAIL: ${USER_EMAIL}
    DOZZLE_AUTH_PASSWORD: ${GENERATED_PWD}
postLaunchNote: |
  Dozzle username: admin, password: ${GENERATED_PWD}
