# Run with docker compose up -d
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:${PORT}:8080"
    depends_on:
      dozzle-generate-users:
        condition: service_completed_successfully
    environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      DOZZLE_ENABLE_ACTIONS: ${DOZZLE_ENABLE_ACTIONS}
      DOZZLE_ENABLE_SHELL: ${DOZZLE_ENABLE_SHELL}
      DOZZLE_AUTH_PROVIDER: ${DOZZLE_AUTH_PROVIDER}
  dozzle-generate-users:
    image: amir20/dozzle:latest
    volumes:
      - ./data
    command: |
      if [ ! -f /data/users.yml ]; then
        generate admin --password "${DOZZLE_AUTH_PASSWORD}" --email "${DOZZLE_AUTH_EMAIL}" --name "Admin" > users.yml
        echo "Users file created"
      else
        echo "Users file already exists"
      fi


