id: evo-ai-frontend
name: EVO AI
intro:  This is Next.js frontend for EVO AI
logo: https://avatars.githubusercontent.com/u/136080052
description: |
  Evo AI is an open-source platform for creating and managing AI agents, 
  enabling integration with different AI models and services. 
tags:
  - oss
  - ai
  - ai-agent
app:
  type: next
  repositoryUrl: https://github.com/EvolutionAPI/evo-ai-frontend
  env:
    PORT: 3005
    API_URL: https://api.example.com
    NEXT_PUBLIC_API_URL: ${API_URL}
