version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "${PORTAINER_PORT}:${PORTAINER_PORT}"
      - "${PORTAINER_AGENT_PORT}:${PORTAINER_AGENT_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data: