id: ghost-cms
name: Ghost CMS
intro: "Ghost is an independent platform for publishing online by web and email newsletter."
logo: https://raw.githubusercontent.com/dollardeploy/templates/refs/heads/main/ghost-cms/157884383-1b75feb1-45d8-4430-b636-3f7e06577347.png
tags:
  - cms
  - blog
  - newsletter
  - oss
  - popular
deployTime: ~3 minutes
description: |
  Ghost is a powerful app for professional publishers to create, share, and 
  grow a business around their content. It comes with modern tools to build a 
  website, publish content, send newsletters & offer paid subscriptions to members.
requirements:
  memory: 2048
  cpu: 2
  storage: 10
services:
  - docker
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourcePath: ghost-cms
  sourceBranch: main
  env:
    SERVER_URL: ${APP_URL}
    MYSQL_PASSWORD: ${GENERATED_PWD}
    PORT: 3000
    MAIL_FROM: example@example.com
    MAIL_HOST: 127.0.0.1
    MAIL_PORT: 485
    MAIL_USERNAME: username
    MAIL_PASSWORD: password
    MAIL_SECURE: false

