x-common:
  panel:
    &panel-environment
    APP_URL: "${APP_URL}"
    ADMIN_EMAIL: "${ADMIN_EMAIL}"

    APP_DEBUG: "false"
    APP_ENV: "production"

  mail:
    &mail-environment
    MAIL_DRIVER: "${MAIL_DRIVER}"
    MAIL_HOST: "${MAIL_HOST}"
    MAIL_PORT: "${MAIL_PORT}"
    MAIL_FROM: "${MAIL_FROM}"
    MAIL_USERNAME: "${MAIL_USERNAME}"
    MAIL_PASSWORD: "${MAIL_PASSWORD}"
    # MAIL_SCHEME: ""

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    build: .
    restart: always
    networks:
      - default
    ports:
      - "${PORT}:80"
      # - "9000:9000" # enable when not using caddy to be able to reach php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway" # shows the panel on the internal docker network as well. usually '172.17.0.1'
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      XDG_DATA_HOME: /pelican-data
      # SKIP_CADDY: true # enable when not using caddy.
  wings:
    image: ghcr.io/pelican-dev/wings:latest
    restart: always
    networks:
      - wings0
    ports:
      - "${PORT_PANEL}:8080"
      - "${PORT_SFTP}:2022"
    tty: true
    environment:
      TZ: "${APP_TIMEZONE}"
      WINGS_UID: "${WINGS_UID}"
      WINGS_GID: "${WINGS_GID}"
      WINGS_USERNAME: "${WINGS_USERNAME}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pelican/:/etc/pelican/"
      - "/var/lib/pelican/:/var/lib/pelican/"
      - "/var/log/pelican/:/var/log/pelican/"
      - "/tmp/pelican/:/tmp/pelican/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"

volumes:
  pelican-data:
  pelican-logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0