id: wikijs
name: Wiki.js
intro: >-
  Wiki.js is a modern, feature-rich, and easy-to-use wiki app built on Node.js.
logo: https://js.wiki/img/wikijs-full-2021.b840e376.svg
requirements:
  memory: 2048
  cpu: 2
  storage: 10
app:
  type: react
  repositoryUrl: https://github.com/requarks/wiki
  sourceBranch: main
  buildScript: build
  startScript: start
  # modify the package.json to set dev: false
  preStartCmd: node -e "const fs = require('fs'); const package = require('./package.json'); package.dev = false; fs.writeFileSync('./package.json', JSON.stringify(package, null, 2));"
  env:
    PORT: 3000
    PGSSLMODE: no-verify
    DATABASE_URL: ${POSTGRES_URL}
  files:
    - path: config.yml
      content: |
        port: 3000
        bindIP: 127.0.0.1
        database:
          type: postgres
          host: localhost
          port: 5432
          user: postgres
          password: postgres
          database: postgres
          ssl: true
          schema: public
          sslOptions:
            auto: false
            rejectUnauthorized: false
        dataPath: ./tmp
introVideoUrl: https://www.youtube-nocookie.com/embed/xjOfL_mMWk4
deployTime: ~10 minutes
description: |
  A modern, lightweight and powerful wiki app built on NodeJS
services:
  - postgres
