id: minio
name: MinIO
intro: High-performance, S3 compatible object store, open sourced under GNU AGPLv3 license.
description: |
  MinIO is a high-performance, S3-compatible object storage solution released under the GNU AGPL v3.0 license. Designed for speed and scalability, it powers AI/ML, analytics, and data-intensive workloads with industry-leading performance. 
  🔹 S3 API Compatible – Seamless integration with existing S3 tools 
  🔹 Built for AI & Analytics – Optimized for large-scale data pipelines
  🔹 High Performance – Ideal for demanding storage workloads.
logo: https://avatars.githubusercontent.com/u/695951
requirements:
  memory: 1024
  cpu: 1
  storage: 10
deployTime: ~5 minutes
tags:
  - storage
  - s3
  - cloud
services:
  - docker
app:
  type: docker-compose
  repositoryUrl: https://github.com/dollardeploy/templates
  sourceBranch: main
  sourcePath: minio
  dockerComposeFile: docker-compose.yml
  env:
    PORT: 9000
    PORT_CONSOLE: 9001
    MINIO_ROOT_USER: ${GENERATED_PWD}
    MINIO_ROOT_PASSWORD: ${GENERATED_HASH}
    MINIO_VERSION: RELEASE.2025-09-07T16-13-09Z
postLaunchNote: |
  You can access S3 