id: openclaw
name: OpenClaw
experimental: true
intro: Self-hosted AI assistant that integrates with WhatsApp, Telegram, Slack, Discord and more
logo: https://avatars.githubusercontent.com/u/252820863
tags:
  - ai
  - assistant
  - automation
  - oss
  - messaging
  - claude
deployTime: ~15 minutes
description: |
  OpenClaw is your own personal AI assistant that runs natively with Node.js and integrates with multiple platforms.
  It provides a unified control center for interacting with AI models through your existing communication
  apps—WhatsApp, Telegram, Slack, Discord, Google Chat, Signal, iMessage, and others.

  Features:
  - Multi-channel messaging integration (WhatsApp, Telegram, Slack, Discord, etc.)
  - Native browser control with VNC server for advanced browser automation
  - Voice interaction and browser automation capabilities
  - Extensible tools including browser control, file operations, and cron scheduling
  - Security-first design with pairing-based access control
  - Canvas visualization and skills registry system

  This template installs OpenClaw natively with:
  - Node.js 22 (via nvm)
  - pnpm package manager
  - VNC server for browser control
  - systemd services for auto-start
  - Browser extension for enhanced capabilities

  After deployment:
  1. The deploy.sh script will handle all installation steps
  2. OpenClaw will be available as a global command
  3. VNC server will run on display :1 (port 5901)
  4. Browser extension will be symlinked to ~/openclaw-extension

requirements:
  memory: 8192
  cpu: 4
  storage: 60
services: []
app:
  type: script
  repositoryUrl: https://github.com/dollardeploy/templates
  sourcePath: openclaw
  sourceBranch: main
  preStartCmd: nohup deploy.sh &
  startScript: server.js
  mainPort: 3000
  env:
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    OPENROUTER_API_KEY: ""
    VNC_PASSWORD: "${GENERATED_PWD}"
postLaunchNote: |
  OpenClaw installation has started! 🚀

  📊 View installation progress and status: ${APP_URL}

  The deploy.sh script is running in the background and will:
  - Install Node.js 22, pnpm, and dependencies
  - Configure VNC server for browser control
  - Install OpenClaw globally
  - Set up systemd services

  Once complete (check the status page):
  1. SSH into your server
  2. Run: openclaw
  3. VNC available at: localhost:5901
  4. Browser extension: ~/openclaw-extension

  📚 Documentation: https://docs.openclaw.ai/
  💻 GitHub: https://github.com/openclaw/openclaw
